import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, { useRef, useEffect} from 'react';
import { Navigation, Pagination, Scrollbar, A11y, Autoplay, } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';

export default function SwiperComp() {
  // inntersection observer start
  const targets = useRef([]);
  const addToTargets = (el: never) => {
    if (el && !targets.current?.includes(el)) {
      targets.current.push(el)
    }
  }
  const options = {
    threshold: 0
  }
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry: any) => {
        if (entry.isIntersecting) {
          entry.target.classList.add(styles.active);
        }
      });
    }, options);
    targets.current.forEach((target) => {
      observer.observe(target);
    });
  }, [targets]);
  // inntersection observer end

  return (
    <>
      <Head >
        <title>Create Next App</title>
        <meta name="Ryotaroのポートフォリオサイトです" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </Head>
        <div ref={addToTargets} className={`${styles.appear} ${styles.swiper_container}`}>
          <Swiper
            //autoplay={{"delay": 1000}} 追記 
            autoplay={{ "delay": 5000 }}
            // デフォルト＋Autoplay, EffectFade追記
            modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
            navigation
            // speed追記
            speed={1000}
            pagination={{ clickable: true }}
            scrollbar={{ draggable: true }}
          >
            <SwiperSlide>
              <div className={`${styles.skill_wrapper}`}>
                <h3><span style={{ marginRight: '5px', verticalAlign: '-5px' }} className="material-symbols-outlined">
                  star
                </span>Skills</h3>
                <p>HTML, CSS, JavaScript, React, Next.js, WordPress, PHP, SQL</p>
                <p>Firebase, Firestore, Git, GitHub, Vercel</p>
                <p>Photoshop, illustrator, XD, Premiere Pro</p>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={`${styles.skill_wrapper}`}>
                <h3><span style={{ marginRight: '5px', verticalAlign: '-5px' }} className="material-symbols-outlined">
                  select_check_box
                </span>About Me</h3>
                <p>～プロフィール～</p>
                <p>＜受注可能な作業内容＞</p>
                <p>ホームページ作成：モダンな言語で高速かつSEOに強いホームページを作成します。</p>
                <p>システム構築：お問い合わせシステム、入力データの保存、データベースアクセス等のシステム構築が可能です。</p>
                <p>稼働時間:50時間/月</p>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={`${styles.skill_wrapper}`}>
                <h3><span style={{ marginRight: '5px', verticalAlign: '-5px' }} className="material-symbols-outlined">
                  arrow_outward
                </span>Objective</h3>
                <p>モダンな言語、堅牢なシステム、型崩れしない表示を目指してコーディングを行います。</p>
                <p>お客様のご要望に何なりと答えられるスキルを得られるよう日々精進しております。</p>
                <p>フロントエンジニアの高みを目指します。</p>
              </div>
            </SwiperSlide>
          </Swiper>
        </div>
    </>
  )
}
