import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 className={styles.title}>Title</h1>
      </header>
      <main className={styles.main}>
        {/* 
        websites
         */}
        <div className={`${styles.container} ${styles.websites_container}`}>
          <h2>Websites</h2>
          <div className={`${styles.wrapper} ${styles.websites_wrapper}`}>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
          </div>
        </div>

        {/* 
        applications
         */}
        <div className={`${styles.container} ${styles.applications_container}`}>
          <h2>Applications</h2>
          <div className={`${styles.wrapper} ${styles.applications_wrapper}`}>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
          </div>
        </div>

        {/* 
        practice
         */}
        <div className={`${styles.container} ${styles.practices_container}`}>
          <h2>Practices</h2>
          <div className={`${styles.wrapper} ${styles.practices_wrapper}`}>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div>
              <h3>site name</h3>
              <h3>feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <h3>
          This page is created by Ryotaro
        </h3>
      </footer>
    </>
  )
}
