import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, { useRef, useEffect } from 'react';
import { Navigation, Pagination, Scrollbar, A11y, Autoplay, } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';

export default function Home() {

  // inntersection observer start
  const targets = useRef([]);
  const addToTargets = (el: never) => {
    if (el && !targets.current?.includes(el)) {
      targets.current.push(el)
    }
  }
  const options = {
    threshold: .2
  }
  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry: any) => {
        if (entry.isIntersecting) {
          entry.target.classList.add(styles.active);
        }
      });
    }, options);
    targets.current.forEach((target) => {
      observer.observe(target);
    });
  }, [targets]);
  // inntersection observer end

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1 ref={addToTargets} className={`${styles.title} ${styles.appear}`}>～Ryotaro's Portfolio～</h1>
      </header>
      <main className={styles.main}>
        <div ref={addToTargets} className={`${styles.appear}`}>
          <Swiper
            //autoplay={{"delay": 1000}} 追記 
            autoplay={{ "delay": 1000 }}
            // デフォルト＋Autoplay, EffectFade追記
            modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
            navigation
            // speed追記
            speed={2000}
            pagination={{ clickable: true }}
            scrollbar={{ draggable: true }}
          >
            <SwiperSlide>
              <div className={`${styles.skill_wrapper}`}>
                <h3>Skills</h3>
                <p>HTML, CSS, JavaScript, React, Next.js, WordPress, PHP, SQL</p>
                <p>Firebase, Firestore, Git, GitHub, Vercel</p>
                <p>Photoshop, illustrator, XD, Premiere Pro</p>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={`${styles.skill_wrapper}`}>
                <h3>About Me</h3>
                <p>HTML, CSS, JavaScript, React, Next.js, WordPress, PHP, SQL</p>
                <p>Firebase, Firestore, Git, GitHub, Vercel</p>
                <p>Photoshop, illustrator, XD, Premiere Pro</p>              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={`${styles.skill_wrapper}`}>
                <h3>Dream</h3>
                <p>HTML, CSS, JavaScript, React, Next.js, WordPress, PHP, SQL</p>
                <p>Firebase, Firestore, Git, GitHub, Vercel</p>
                <p>Photoshop, illustrator, XD, Premiere Pro</p>              </div>
            </SwiperSlide>
          </Swiper>

        </div>
        {/* 
        websites
      */}
        <div ref={addToTargets} className={`${styles.container} ${styles.websites_container} ${styles.appear}`}>
          <h2>Websites</h2>
          <div className={`${styles.wrapper} ${styles.websites_wrapper}`}>
            <div ref={addToTargets} className={`${styles.sanpatuya} ${styles.appear}`}>
              <a href="https://xs622417.xsrv.jp/homepage_test/index.html" target='_blank'>
                <h3>ザ・サンパツヤ</h3>
                <p className={styles.url_p}>url: https://xs622417.xsrv.jp/homepage_test/index.html</p>
              </a>
              <hr />
              <a href="https://github.com/ryotaro-0805/homepage-kankyokaihatu" target='_blank'>
                <p className={styles.code_p}>code: https://github.com/ryotaro-0805/homepage-kankyokaihatu</p>
              </a>
              <hr />
              <h3>Feature / 特徴</h3>
              <p>『キュート』、『親しみ』をテーマにHTML,CSS,JavaScriptで作成しております。</p>
              <p>SEO対策も施しているため、架空のショップサイトですがGoogleでの検索順位は上位となっています。</p>
            </div>

            <div ref={addToTargets} className={`${styles.kankyo} ${styles.appear}`}>
              <a href="https://homepage-kankyokaihatu.vercel.app" target='_blank'>
                <h3>環境開発株式会社</h3>
                <p className={styles.url_p}>url: https://homepage-kankyokaihatu.vercel.app/</p>
              </a>
              <hr />
              <a href="https://github.com/ryotaro-0805/homepage-kankyokaihatu" target='_blank'>
                <p className={styles.code_p}>code: https://github.com/ryotaro-0805/homepage-kankyokaihatu</p>
              </a>
              <hr />
              <h3>Feature / 特徴</h3>
              <p>『環境』、『ビジネス』をテーマにNext.jsで作成しております。</p>
              <p></p>
            </div>

            <div ref={addToTargets} className={`${styles.seto} ${styles.appear}`}>
              <h3>瀬戸珈琲</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>

            <div ref={addToTargets} className={`${styles.site} ${styles.appear}`}>
              <h3>site name</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
          </div>
        </div>

        {/* 
        applications
         */}
        <div ref={addToTargets} className={`${styles.container} ${styles.applications_container} ${styles.appear}`}>
          <h2>Applications</h2>
          <div className={`${styles.wrapper} ${styles.applications_wrapper}`}>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>ToDoアプリ</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>じゃんけん</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>スロット</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>仕事効率化</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
          </div>
        </div>

        {/* 
        practice
         */}
        <div ref={addToTargets} className={`${styles.container} ${styles.practices_container} ${styles.appear}`}>
          <h2>Practices</h2>
          <div className={`${styles.wrapper} ${styles.practices_wrapper}`}>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>Swiper</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>流れる文字</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>自由に移動</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
            <div ref={addToTargets} className={`${styles.appear}`}>
              <h3>useful App</h3>
              <h3>Feature</h3>
              <p>texttexttext</p>
              <h3>trouble point</h3>
              <p>texttexttext</p>
            </div>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        <h3>
          This page is created by Ryotaro
        </h3>
      </footer>
    </>
  )
}
